/**
 * React main.tsx Entry Point Generator
 *
 * Generates the main.tsx entry point for React application
 */

import type { TemplateContext } from '../../../../../src/realize/types/index.js';

/**
 * Generate main.tsx React entry point
 */
export default function generateMainTsx(context: TemplateContext): string {
  return `/**
 * React Application Entry Point
 * Auto-generated by SpecVerse
 */

import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
`;
}
