/**
 * React index.html Generator
 *
 * Generates the HTML entry point for a React application
 */

import type { TemplateContext } from '../../../../../src/realize/types/index.js';

/**
 * Generate index.html for React application
 */
export default function generateIndexHtml(context: TemplateContext): string {
  const { spec } = context;

  // Extract component name from spec metadata
  const componentName = spec?.metadata?.component || spec?.component?.name || 'App';
  const description = spec?.metadata?.description || spec?.component?.description || 'Generated by SpecVerse';

  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="${description}" />
    <title>${componentName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;
}
