/**
 * React index.css Generator
 *
 * Generates base CSS styles for React application
 */

import type { TemplateContext } from '@specverse/engine-realize';

/**
 * Generate index.css with base styles
 */
export default function generateIndexCss(context: TemplateContext): string {
  return `/**
 * Base CSS Styles
 * Auto-generated by SpecVerse
 */

:root {
  font-family: Inter, system-ui, Avenir, Helvetica, Arial, sans-serif;
  line-height: 1.5;
  font-weight: 400;

  color-scheme: light dark;
  color: rgba(255, 255, 255, 0.87);
  background-color: #242424;

  font-synthesis: none;
  text-rendering: optimizeLegibility;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

a {
  font-weight: 500;
  color: #646cff;
  text-decoration: inherit;
}

a:hover {
  color: #535bf2;
}

body {
  margin: 0;
  display: flex;
  place-items: center;
  min-width: 320px;
  min-height: 100vh;
}

h1 {
  font-size: 3.2em;
  line-height: 1.1;
}

button {
  border-radius: 8px;
  border: 1px solid transparent;
  padding: 0.6em 1.2em;
  font-size: 1em;
  font-weight: 500;
  font-family: inherit;
  background-color: #1a1a1a;
  cursor: pointer;
  transition: border-color 0.25s;
}

button:hover {
  border-color: #646cff;
}

button:focus,
button:focus-visible {
  outline: 4px auto -webkit-focus-ring-color;
}

@media (prefers-color-scheme: light) {
  :root {
    color: #213547;
    background-color: #ffffff;
  }

  a:hover {
    color: #747bff;
  }

  button {
    background-color: #f9f9f9;
  }
}

#root {
  max-width: 1280px;
  margin: 0 auto;
  padding: 2rem;
  text-align: center;
}

.app-container {
  width: 100%;
}

/* Home page styles */
.home-page {
  text-align: left;
}

.home-page nav {
  margin-top: 2rem;
}

.home-page ul {
  list-style: none;
  padding: 0;
}

.home-page li {
  margin: 0.5rem 0;
}

.home-page a {
  display: inline-block;
  padding: 0.5rem 1rem;
  border-radius: 4px;
  background-color: #1a1a1a;
  text-decoration: none;
}

.home-page a:hover {
  background-color: #2a2a2a;
}

/* Form styles */
form {
  display: flex;
  flex-direction: column;
  gap: 1rem;
  max-width: 500px;
  margin: 2rem auto;
  text-align: left;
}

form label {
  display: block;
  margin-bottom: 0.25rem;
  font-weight: 500;
}

form input,
form textarea,
form select {
  width: 100%;
  padding: 0.5rem;
  border: 1px solid #ccc;
  border-radius: 4px;
  font-family: inherit;
  font-size: 1em;
}

form input:focus,
form textarea:focus,
form select:focus {
  outline: 2px solid #646cff;
}

form .error {
  color: #ff4444;
  font-size: 0.875em;
  margin-top: 0.25rem;
}

/* Table styles */
table {
  width: 100%;
  border-collapse: collapse;
  margin: 2rem 0;
}

table th,
table td {
  padding: 0.75rem;
  text-align: left;
  border-bottom: 1px solid #ddd;
}

table th {
  background-color: #1a1a1a;
  font-weight: 600;
}

table tr:hover {
  background-color: #2a2a2a;
}

/* Loading and error states */
.loading {
  padding: 2rem;
  text-align: center;
}

.error-message {
  padding: 1rem;
  background-color: #ff4444;
  color: white;
  border-radius: 4px;
  margin: 1rem 0;
}
`;
}
