/**
 * React Router Generator (Generic Renderers)
 *
 * Generates router.tsx that uses locally generated view components
 */

import type { TemplateContext } from '../../../../../src/realize/types/index.js';

/**
 * Generate router.tsx with generic renderers
 */
export default function generateRouter(context: TemplateContext): string {
  const { spec, models = [], views = [] } = context;

  // Extract views from spec if not provided
  const specViews = views.length > 0 ? views : (spec?.views || []);
  const viewsArray = Array.isArray(specViews) ? specViews : Object.values(specViews);

  // Generate route entries
  const routes: string[] = [];

  // Track used paths to ensure uniqueness
  const usedPaths = new Set<string>();

  // Generate routes for each view
  viewsArray.forEach((viewDef: any) => {
    const viewName = viewDef.name;
    const viewType = viewDef.type || 'list';
    const model = Array.isArray(viewDef.model) ? viewDef.model[0] : viewDef.model;

    if (!model) return;

    const modelLower = model.toLowerCase();
    const modelPlural = modelLower + 's'; // Simple pluralization

    // Determine which generic renderer to use
    const rendererName = getRendererForType(viewType);

    // Generate unique path based on view type
    const basePath = `/${modelPlural}`;

    switch (viewType) {
      case 'list':
        const listPath = usedPaths.has(basePath)
          ? `${basePath}/${viewName.toLowerCase().replace(/view$/, '')}`
          : basePath;

        if (!usedPaths.has(listPath)) {
          routes.push(`  {
    path: '${listPath}',
    element: <${rendererName} view={viewsMetadata.${viewName}} spec={spec} />
  }`);
          usedPaths.add(listPath);
        }
        break;

      case 'detail':
        const detailPath = `${basePath}/:id`;
        if (!usedPaths.has(detailPath)) {
          routes.push(`  {
    path: '${detailPath}',
    element: <${rendererName} view={viewsMetadata.${viewName}} spec={spec} />
  }`);
          usedPaths.add(detailPath);
        }
        break;

      case 'form':
      case 'create-form':
        const newPath = `${basePath}/new`;
        if (!usedPaths.has(newPath)) {
          routes.push(`  {
    path: '${newPath}',
    element: <${rendererName} view={viewsMetadata.${viewName}} spec={spec} />
  }`);
          usedPaths.add(newPath);
        }
        break;

      case 'edit-form':
        const editPath = `${basePath}/:id/edit`;
        if (!usedPaths.has(editPath)) {
          routes.push(`  {
    path: '${editPath}',
    element: <${rendererName} view={viewsMetadata.${viewName}} spec={spec} />
  }`);
          usedPaths.add(editPath);
        }
        break;

      case 'dashboard':
        const dashPath = `${basePath}/dashboard`;
        if (!usedPaths.has(dashPath)) {
          routes.push(`  {
    path: '${dashPath}',
    element: <${rendererName} view={viewsMetadata.${viewName}} spec={spec} />
  }`);
          usedPaths.add(dashPath);
        }
        break;
    }
  });

  // Add home route with navigation
  const homeLinks = viewsArray.map((viewDef: any) => {
    const viewName = viewDef.name;
    const model = Array.isArray(viewDef.model) ? viewDef.model[0] : viewDef.model;
    const modelLower = model?.toLowerCase() || 'unknown';
    const path = getPathForView(viewDef, modelLower);
    return `          <li><a href="${path}">${viewName}</a></li>`;
  }).join('\n');

  routes.unshift(`  {
    path: '/',
    element: (
      <div className="home-page">
        <h1>Welcome</h1>
        <nav>
          <ul>
${homeLinks}
          </ul>
        </nav>
      </div>
    )
  }`);

  return `/**
 * React Router Configuration
 * Auto-generated by SpecVerse
 */

import { createBrowserRouter } from 'react-router-dom';
import { FormView, ListView, DetailView, DashboardView } from './components';
import viewsMetadata from './views-metadata.json';
import spec from './spec.json';

/**
 * Application routes
 */
export const router = createBrowserRouter([
${routes.join(',\n')}
]);
`;
}

/**
 * Get renderer component name for view type
 */
function getRendererForType(viewType: string): string {
  const rendererMap: Record<string, string> = {
    'list': 'ListView',
    'detail': 'DetailView',
    'form': 'FormView',
    'create-form': 'FormView',
    'edit-form': 'FormView',
    'dashboard': 'DashboardView'
  };

  return rendererMap[viewType] || 'ListView';
}

/**
 * Get path for view based on type
 */
function getPathForView(viewDef: any, modelLower: string): string {
  const basePath = `/${modelLower}s`;
  const viewType = viewDef.type || 'list';

  switch (viewType) {
    case 'detail':
      return `${basePath}/1`; // Example ID
    case 'form':
    case 'create-form':
      return `${basePath}/new`;
    case 'edit-form':
      return `${basePath}/1/edit`;
    case 'dashboard':
      return `${basePath}/dashboard`;
    default:
      return basePath;
  }
}
